[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "explain bargain gesture present humor clap diamond jaguar square civil victory reform turkey pulse lamp priority exotic fork push blush decide layer divert under"
